services:
  redis:
    image: redis:7-alpine
    container_name: bd-lab5-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_lab5_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

volumes:
  redis_lab5_data:
