BEGIN
  EXECUTE IMMEDIATE 'DROP USER DEV_SCHEMA CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP USER PROD_SCHEMA CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE USER DEV_SCHEMA  IDENTIFIED BY dev123  DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
CREATE USER PROD_SCHEMA IDENTIFIED BY prod123 DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, CREATE VIEW TO DEV_SCHEMA;
GRANT CONNECT, RESOURCE, CREATE VIEW TO PROD_SCHEMA;