-- Seed objects for Lab 3 compare (run as SYSTEM or SYSDBA)
SET DEFINE OFF

-- DEV schema: recreate demo objects
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DEV_SCHEMA.ORDERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DEV_SCHEMA.USERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DEV_SCHEMA.PRODUCTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION DEV_SCHEMA.USER_EXISTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE DEV_SCHEMA.ADD_ORDER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE DEV_SCHEMA.UPDATE_PRODUCT_PRICE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE DEV_SCHEMA.UPDATE_USER_EMAIL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE DEV_SCHEMA.DELETE_USER_BY_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE DEV_SCHEMA.USER_PKG'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE DEV_SCHEMA.PRODUCTS (
    ID       NUMBER PRIMARY KEY,
    NAME     VARCHAR2(100) NOT NULL,
    PRICE    NUMBER(10,2),
    CATEGORY VARCHAR2(50)
);

CREATE TABLE DEV_SCHEMA.USERS (
    ID       NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL,
    EMAIL    VARCHAR2(100)
);

CREATE TABLE DEV_SCHEMA.ORDERS (
    ID        NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER,
    QUANTITY   NUMBER,
    CONSTRAINT FK_ORDERS_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES DEV_SCHEMA.PRODUCTS(ID)
);

CREATE INDEX DEV_SCHEMA.IDX_PRODUCTS_NAME ON DEV_SCHEMA.PRODUCTS(NAME);
CREATE INDEX DEV_SCHEMA.IDX_ORDERS_PROD  ON DEV_SCHEMA.ORDERS(PRODUCT_ID);

CREATE OR REPLACE FUNCTION DEV_SCHEMA.USER_EXISTS(p_user_id IN NUMBER) RETURN NUMBER IS
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM DEV_SCHEMA.USERS WHERE ID = p_user_id;
    RETURN CASE WHEN v_cnt > 0 THEN 1 ELSE 0 END;
END;
/

CREATE OR REPLACE PROCEDURE DEV_SCHEMA.ADD_ORDER(
    p_product_id IN NUMBER,
    p_quantity   IN NUMBER
) IS
BEGIN
    INSERT INTO DEV_SCHEMA.ORDERS(ID, PRODUCT_ID, QUANTITY)
    VALUES (NVL((SELECT MAX(ID)+1 FROM DEV_SCHEMA.ORDERS), 1), p_product_id, p_quantity);
END;
/

CREATE OR REPLACE PROCEDURE DEV_SCHEMA.UPDATE_PRODUCT_PRICE(
    p_product_id IN NUMBER,
    p_new_price  IN NUMBER
) IS
BEGIN
    UPDATE DEV_SCHEMA.PRODUCTS
       SET PRICE = p_new_price
     WHERE ID = p_product_id;
END;
/

CREATE OR REPLACE PROCEDURE DEV_SCHEMA.UPDATE_USER_EMAIL(
    p_user_id   IN NUMBER,
    p_new_email IN VARCHAR2
) IS
BEGIN
    UPDATE DEV_SCHEMA.USERS
       SET EMAIL = p_new_email
     WHERE ID = p_user_id;
END;
/

CREATE OR REPLACE PROCEDURE DEV_SCHEMA.DELETE_USER_BY_ID(
    p_user_id IN NUMBER
) IS
BEGIN
    DELETE FROM DEV_SCHEMA.USERS
     WHERE ID = p_user_id;
END;
/

CREATE OR REPLACE PACKAGE DEV_SCHEMA.USER_PKG IS
    FUNCTION get_user_count RETURN NUMBER;
END USER_PKG;
/

CREATE OR REPLACE PACKAGE BODY DEV_SCHEMA.USER_PKG IS
    FUNCTION get_user_count RETURN NUMBER IS
        v_cnt NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_cnt FROM DEV_SCHEMA.USERS;
        RETURN v_cnt;
    END;
END USER_PKG;
/

-- PROD schema: create intentionally different subset
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PROD_SCHEMA.LEGACY_LOG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PROD_SCHEMA.PRODUCTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE PROD_SCHEMA.PRODUCTS (
    ID    NUMBER PRIMARY KEY,
    NAME  VARCHAR2(100) NOT NULL,
    PRICE NUMBER(10,2)
);

CREATE TABLE PROD_SCHEMA.LEGACY_LOG (
    ID      NUMBER PRIMARY KEY,
    MESSAGE VARCHAR2(500)
);

COMMIT;
